# Generated by Django 4.1.7 on 2023-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bookFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bookUpto',
            field=models.DateField(),
        ),
    ]
