# Generated by Django 4.1.7 on 2023-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='totalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
